### ISSUE TITLE
🐞 Debug survey page refresh/clear

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#341]
Running an experiment with about 50 real participants, about 10% of people had trouble with the surveys:

> When selecting my answers in the survey afterwards, my selections was disappear and I am not sure if they were recorded. This also happened when putting in my personal details / demographic info at the end and meant I had to go select the same answers again and again as it kept sending me back to questions saying I hadn't answered them because the answers kept on disappearing

> Technical issues with the questionnaire, where the selected answers would disappear 

> Answering the questions. The tick boxes would not accept the ticks and kept resetting so I had to do them multiple time till they worked.

> When using scroll down bar on my Mac, the comments or comment responses would turn blank and I would be returned to the top of the page. I overcame this by using the arrow keys to scroll down.

> On any questionnaire screen - I would complete the questions and they disappeared.  I had to complete two pages twice and the second time it would be a race to complete before the responses deleted

> On any questionnaire screen - I would complete the questions and they disappeared.  I had to complete two pages twice and the second time it would be a race to complete before the responses deleted

> On any questionnaire screen - I would complete the questions and they disappeared.  I had to complete two pages twice and the second time it would be a race to complete before the responses deleted

This seems like a disconnect/reconnect issue. From Nicolas:

> A disconnection should clear the screen. Not sure what you were testing, but I am fairly certain a disconnection will “un-render”, even in the exit steps. We still have the Player object, which is dependent on the connection being alive.

A browser refresh will clear participant selections.

**Comment by JamesPHoughton** [comment]
Looks like there are more connection events per user than I would have expected:

![Image](https://user-images.githubusercontent.com/4304478/203345635-78014668-9203-4b5d-8cc1-8f6d1cf2a2f6.png)

Here's the timeseries of up/down for each user:

![Image](https://user-images.githubusercontent.com/4304478/203345817-0102e926-cacd-4edb-9228-1992699671ee.png)

**Comment by JamesPHoughton** [comment]
Logs from the server tracking disconnections connected to participant feedback:

sessionId | reconnects | technicalProblems | technicalDetail
-- | -- | -- | --
01GJDCV88KB60FPCK2RCHFDQEX | 2.0 | yes | Answering the questions. The tick boxes would not accept the ticks and kept resetting so I had to do them multiple time till they worked.
01GJDJEMPVWH9FPT9NN5CKTYDP | 1.0 | no | I didn't feel I had enough time to answer the questions, especially as one of the screens had a bug which took me a while to figure out.
01GJDCJDZ50QBWPK0369AZXZ96 | 2.0 | yes | The video would occasionally cut-out and then re-join.
01GJDHZ3FHD2Q47Q5KDH43X8BB | 2.0 | yes | On any questionnaire screen - I would complete the questions and they disappeared.  I had to complete two pages twice and the second time it would be a race to complete before the responses deleted
01GJDC4B9NDXMZJH01WDK0CADB | 3.0 | no | Technical issues with the questionnaire, where the selected answers would disappear
01GJDC1VANFPMTYH9925VMY5AQ | 4.0 | no | When selecting my answers in the survey afterwards, my selections was disappear and I am not sure if they were recorded. This also happened when putting in my personal details / demographic info at the end and meant I had to go select the same answers again and again as it kept sending me back to questions saying I hadn't answered them because the answers kept on disappearing
01GJDD4A9W6ZK9T96EMGPX0GVF | 11.0 | yes | When using scroll down bar on my Mac, the comments or comment responses would turn blank and I would be returned to the top of the page. I overcame this by using the arrow keys to scroll down.
01GJDDAJJSZ0BSEDH4D6KCQ714 | 1.0 | yes | The green boxes to give feedback on the conversation kept refreshing to blank on the first 3 screens and it was impossible to submit answers
01GJDHQQM4Z6B0RBACAZHHAD5T | 2.0 | yes | crackling on the video and cut out briefly. also one page timed out before I could complete the question
01GJDJ11FJ3WHYXN7EBC7MPSVS | 2.0 | yes | Selecting the answers would make them disappear again after some time so that you couldn't answer all the questions and submit it.  I had to go back and try to answer the questions quickly and submitted before they disappeared again.
01GJDK5656Z96DQ968QABCNW6J | 2.0 | yes | The video was blank for about 4 seconds


It doesn't seem that all of the refreshing can be blamed on disconnect/reconnect (at least as measured by the server)

**Comment by JamesPHoughton** [comment]
When I load a survey on the prod server, and then turn off my internet connection, I don't see the survey answers disappear or go blank. Instead, the survey stays rendered, but when I go to submit the survey, instead of being directed to the next phase in the experiment, I see the surveyJS standard "thank you for completing the survey" form for a while,and then the page goes blank. I get a console log:
```
index.a62973a8.js:10585 Uncaught TypeError: Cannot read properties of undefined (reading 'set')
    at index.a62973a8.js:58989:12
    at Rj (index.a62973a8.js:10702:334)
    at Ik (index.a62973a8.js:10744:117)
    at Xk (index.a62973a8.js:10741:430)
    at Qk (index.a62973a8.js:10739:422)
    at Fk (index.a62973a8.js:10731:451)
    at jg (index.a62973a8.js:10585:109)
    at index.a62973a8.js:10725:279
```
which is happening on the first render of the next page, at the first interaction with the player object.
![image](https://user-images.githubusercontent.com/4304478/203596903-879de835-e768-4299-973d-94e70d782100.png)

This tells me that the disconnection is loosing the player object, but it doesn't seem to cause an immediate re-render.

**Comment by JamesPHoughton** [comment]
To unmount in tests: https://github.com/cypress-io/cypress/issues/17959#issuecomment-1305106366

**Comment by JamesPHoughton** [comment]
Unmount didn't work, so moved to multiple tests, setting and checking localstorage manually. 
Changed surveys library to save state whenever there is a value changed here: https://github.com/Watts-Lab/surveys/pull/97

**Comment by JamesPHoughton** [comment]
I've assumed that this problem was mostly present during the SurveyJS post-surveys, but its also possible that we'd see the same behavior with the prompts. Probably ought to look at that next.

**Comment by JamesPHoughton** [comment]
Running an internal test today, we had a problem where the radiobuttons would clear during prompt stages, not surveyjs stages - unclear if this is exactly what the participants saw last week, but need to debug.

**Comment by JamesPHoughton** [comment]
Interestingly, the saving behavior is working properly. What isn't working well is that if you click the second radio button in a set, and another question in the set has the same radio button selected, it will deselect the other question's second radio button. It behaves as if you can only answer option 2 to at most one question. Very strange.

**Comment by JamesPHoughton** [comment]
[Bingo.](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/radio#defining_a_radio_group):
> A radio group is defined by giving each of radio buttons in the group the same [name](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input#attr-name). Once a radio group is established, selecting any radio button in that group automatically deselects any currently-selected radio button in the same group.

I was lazily setting the 'name' attribute to the key, so the HTML page was treating all first options as a radio group, all second options as a different radio group, etc.
