### ISSUE TITLE
Tests in Deliberation Empirica lead to `ERR_INVALID_ARG_TYPE`

### ISSUE THREAD

**Issue by xehu** [Watts-Lab/deliberation-empirica#607]
I was trying to test some of the latest Deliberation updates, but in each case, Deliberation Empirica failed to launch the batch with the following:

```
[server] Failed to create batch with config: {"batchName":"3waynegotiation","useData":"false","treatmentFile":"projects/3-way-negotiation/treatments.3_way_negotiation.yaml","dispatchWait":10,"treatments":["Baseline"],"cdn":"local","platformConsent":"US","videoStorageLocation":"deliberation-lab-recordings-test","dataRepos":[{"owner":"Watts-Lab","repo":"tpm-negotiation-data","branch":"main","directory":"test"}]} /Users/xehu/Desktop/deliberation-empirica/server/src/getTreatments.js:183
[server]     throw new Error(
[server]           ^
[server] 
[server] Error: Failed to fetch treatment file from cdn: local path: projects/3-way-negotiation/treatments.3_way_negotiation.yaml
[server]     at <anonymous> (/Users/xehu/Desktop/deliberation-empirica/server/src/getTreatments.js:183:11)
[server]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[server]     at eY (/Users/xehu/Desktop/deliberation-empirica/server/src/getTreatments.js:182:16)
[server]     at Object.callback (/Users/xehu/Desktop/deliberation-empirica/server/src/callbacks.js:92:45)
[server]     at <anonymous> (/Users/xehu/Desktop/deliberation-empirica/server/node_modules/@empirica/core/src/admin/cake.ts:227:15)
[server] Github authentication succeeded with token ****WnQ1
[server] 15:22:25.025 WRN unknown batch status: failed
[server] Batch 01HA08Q10VYTT2FZH90E5A63G0 changed status to "failed"
[server] Batch 01HA08Q10VYTT2FZH90E5A63G0 closed
[server] Currently recruiting for batch:  undefined with config:  undefined
[server] Batch 01HA08Q10VYTT2FZH90E5A63G0 changed status to "failed"
[server] Batch 01HA08Q10VYTT2FZH90E5A63G0 closed
[server] Currently recruiting for batch:  undefined with config:  undefined
[server] TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
[server]     at __node_internal_captureLargerStackTrace (node:internal/errors:477:5)
[server]     at new NodeError (node:internal/errors:387:5)
[server]     at validateString (node:internal/validators:121:11)
[server]     at Object.basename (node:path:1309:5)
[server]     at JK (/Users/xehu/Desktop/deliberation-empirica/server/src/github.js:65:25)
[server]     at dY (/Users/xehu/Desktop/deliberation-empirica/server/src/callbacks.js:204:9)
[server]     at GLe (/Users/xehu/Desktop/deliberation-empirica/server/src/callbacks.js:235:3)
[server]     at Object.callback (/Users/xehu/Desktop/deliberation-empirica/server/src/callbacks.js:161:5)
[server]     at Object.next (/Users/xehu/Desktop/deliberation-empirica/server/node_modules/@empirica/core/src/admin/cake.ts:320:30) {
[server]   code: 'ERR_INVALID_ARG_TYPE'
[server] }
```

Is there perhaps a bug, or is this user error? (Tagging @JamesPHoughton for some help!)

**Comment by JamesPHoughton** [comment]
Looks like you have to restart the local cdn - the command is in the
deliberation-assets root readme…

**Comment by xehu** [comment]
Thank you for the tip! I realized there were two interlocking issues --- restarting the CDN and not having the latest update from `main` in deliberation-empirica. Once I pulled from main, though, I was asked to provide a bunch of new environment variables that I previously did not need when running locally (specifically, the system asked for GITHUB_PRIVATE_DATA_OWNER, GITHUB_PUBLIC_DATA_OWNER, GITHUB_PRIVATE_DATA_REPO, GITHUB_PUBLIC_DATA_REPO,  ... and so on).

I pointed these environment variables originally to my private repo (https://github.com/Watts-Lab/tpm-negotiation-data), and when it returned with a 404, added a public version (https://github.com/Watts-Lab/tpm-negotiation-data-public), as follows:

```
GITHUB_PRIVATE_DATA_OWNER=xehu
GITHUB_PUBLIC_DATA_OWNER=xehu
GITHUB_PRIVATE_DATA_REPO=https://github.com/Watts-Lab/tpm-negotiation-data
GITHUB_PRIVATE_DATA_BRANCH=main
GITHUB_PUBLIC_DATA_REPO=https://github.com/Watts-Lab/tpm-negotiation-data-public
GITHUB_PUBLIC_DATA_BRANCH=main
```

Once I provided these keys, the system fails upon batch launch as follows:
```
[server] Failed to create batch with config: {"batchName":"3waynegotiation","useData":"false","treatmentFile":"projects/3-way-negotiation/treatments.3_way_negotiation.yaml","dispatchWait":10,"treatments":["Baseline"],"cdn":"local","platformConsent":"US","videoStorageLocation":"deliberation-lab-recordings-test","dataRepos":[{"owner":"Watts-Lab","repo":"tpm-negotiation-data","branch":"main","directory":"test"}]} /Users/xehu/Desktop/deliberation-empirica/server/src/github.js:115
[server]       throw new Error(
[server]             ^
[server] 
[server] Error: Error committing file batch_1694386381417_3waynegotiation.jsonl to repository Watts-Lab/tpm-negotiation-data/main/test
[server]     at tY (/Users/xehu/Desktop/deliberation-empirica/server/src/github.js:115:13)
[server]     at <anonymous> (/Users/xehu/Desktop/deliberation-empirica/server/src/github.js:193:9)
[server]     at async Promise.all (index 0)
[server]     at u (/Users/xehu/Desktop/deliberation-empirica/server/src/github.js:189:5)
[server]     at x3 (/Users/xehu/Desktop/deliberation-empirica/server/src/github.js:207:5)
[server]     at Object.callback (/Users/xehu/Desktop/deliberation-empirica/server/src/callbacks.js:131:7)
[server]     at <anonymous> (/Users/xehu/Desktop/deliberation-empirica/server/node_modules/@empirica/core/src/admin/cake.ts:227:15)
[server] 18:53:02.114 WRN unknown batch status: failed
[server] Batch 01HA0MRP981MJSSE4JG57P0P6C changed status to "failed"
[server] Batch 01HA0MRP981MJSSE4JG57P0P6C closed
[server] Currently recruiting for batch:  undefined with config:  undefined
```

It seems like there's an error pushing the data to the GitHub repo? Oddly enough, previously I was running deliberation without the data repos, as I am still testing and don't need to push anything to GitHub. I wonder what happened...?
