### ISSUE TITLE
Tajriba.emit error

### ISSUE THREAD

**Issue by JamesPHoughton** [Watts-Lab/deliberation-empirica#772]
Participants see a white screen, and in my sentry logs I see:
```
Error: Unhandled error. (undefined)
  at Tajriba.emit(/assets/index.8f633f52.js:33507:15)
  at error(/assets/index.8f633f52.js:33944:16)
  at Object.emit(/assets/index.8f633f52.js:24654:21)
  at socket.onerror(/assets/index.8f633f52.js:24712:47)
```

Probably related to:
https://github.com/empiricaly/empirica/issues/483

In that issue, the server reconnected on its own. Unfortunately ours doesn't, and users stay on the white page indefinitely.

I've seen the issue associated with a fully blank screen, and also when the "report bugs" is still available:
![Image](https://github.com/Watts-Lab/deliberation-empirica/assets/4304478/8dce3244-0050-439d-9945-b8bd994d3dd4)

Seems to occur in about 5% of participants.

**Comment by JamesPHoughton** [comment]
notes from nicolas:
> A disconnection shouldn't trigger an "Unhandled error". It should reconnect cleanly.
>
> Avoiding disconnections entirely is impossible, though I'd hope for them to be relatively rare. 5% seems like a rather high number to me. I don't know how long your experiments go for, maybe with long enough connections, disconnections will eventually happen at that rate. It could also be your environment, whatever reverse proxy or load balancer you're using (maybe some default timeout, or it's not very stable with long-running connections). That being said, even if it were 0.1%, we'd still want the client to be able to reconnect automatically. Just saying this to see if there might be a special reason you're seeing this because of your environment.
>
> 2 things in the short terms you can try:
> - you might want to increase the idle_timeout on your load balancer aws_lb.  While this could help, it is a bit odd, since the default seems to be 60s, and there should be a ping on the websocket every 5 or 10s. So it doesn't completely make sense. Though maybe these are not noticed by the load balancer for some reason (payload too small :shrug:) https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lb#idle_timeout
> - Maybe you can add a React Error Boundary at the top of the React tree and catch this error, and reload the page when you see it. https://docs.sentry.io/platforms/javascript/guides/react/features/error-boundary/ Maybe in the fallback, add a useEffect with an empty dependency array, and in there you wait 5 seconds (to let sentry report the error, maybe, I don't know if it needs that or will report the error – I think so, since they offer a custom error boundary) and then reload the page. And you can show a message saying an error was detected, reloading. I don't know if this will work, I have not had a chance to test it. I'm actually a bit suspicious whether the error will be triggered in the React tree or not. If not, I guess the best place to catch the error is in an unhandledrejection. But I'm not sure. https://developer.mozilla.org/en-US/docs/Web/API/Window/unhandledrejection_event

**Comment by JamesPHoughton** [comment]
Added react error boundary to catch this in https://github.com/Watts-Lab/deliberation-empirica/pull/828
